/**
 * RaceHorseTester -- to test the RaceHorse class in which you have to write
 * a default constructor, a constructor with parameters and a toString method.
 * DO NOT EDIT THIS FILE.
 */
public class RaceHorseTester
{
    public static void main(String[] args)
    {
        System.out.println("------ TEST 1: Check that the default constructor and toString work ------");
        Horse defaultHorse = new Horse();
        runToStringTest(defaultHorse, "Horse[name = Horse, year = 2024]");

        RaceHorse defaultRaceHorse = new RaceHorse();
        runToStringTest(defaultRaceHorse, "RaceHorse[name = Horse, year = 2024][trainer = tbd, wins = 0, places = 0, losses = 0]");

        System.out.println("------ TEST 2: Check that the other constructor and toString work ------");
        Horse george = new Horse("George", 2021);
        runToStringTest(george, "Horse[name = George, year = 2021]");

        RaceHorse blaze = new RaceHorse("Blaze", 2009, "Charles");
        runToStringTest(blaze, "RaceHorse[name = Blaze, year = 2009][trainer = Charles, wins = 0, places = 0, losses = 0]");

        System.out.println("------ TEST 3: Add Results ------");

        System.out.println("Add 1 place and 2 losses");
        blaze.record(RaceHorse.Outcome.PLACE);
        blaze.record(RaceHorse.Outcome.LOSS);
        blaze.record(RaceHorse.Outcome.LOSS);
        runToStringTest(blaze, "RaceHorse[name = Blaze, year = 2009][trainer = Charles, wins = 0, places = 1, losses = 2]");

        System.out.println("Add 2 places and a win");
        blaze.record(RaceHorse.Outcome.PLACE);
        blaze.record(RaceHorse.Outcome.PLACE);
        blaze.record(RaceHorse.Outcome.WIN);
        runToStringTest(blaze, "RaceHorse[name = Blaze, year = 2009][trainer = Charles, wins = 1, places = 3, losses = 2]");
    }

    public static void runToStringTest(Horse h, String expected)
    {
        String output = h.toString();
        printTestResult(testStringOutput("toString", output, expected));
    }

    public static void printTestResult(boolean pass)
    {
        if (pass) {
            System.out.println("*** TEST PASSES ***\n");
        } else {
            System.out.println("*******************************************");
            System.out.println("*************** TEST FAILED ***************");
            System.out.println("*******************************************\n");
        }
    }

    public static boolean testStringOutput(String methodName, String output, String expected)
    {
        System.out.println("OUTPUT of " + methodName + ":   " + output);
        if (!output.equals(expected)) {
            System.out.println("EXPECTED of " + methodName + ": " + expected);
            System.out.println("    INCORRECT OUTPUT");
            return false;
        }
        return true;
    }
}

