import java.util.Arrays;

/**
 * This program tests the measurable Country class. DO NOT EDIT THIS FILE.
 */
public class CountryTester
{
    public static void main(String[] args)
    {
        Measurable[] countries = new Measurable[3];
        countries[0] = new Country("Uruguay", 176220);
        countries[1] = new Country("Thailand", 513120);
        countries[2] = new Country("Belgium", 30510);

        System.out.println("------ TEST 1: Test GetMeasure Directly ------");
        runGetMeasureTest(countries[0], 176220.0);
        runGetMeasureTest(countries[1], 513120.0);
        runGetMeasureTest(countries[2], 30510.0);

        System.out.println("------ TEST 2: Test Using Measurable Methods ------");
        runMeasurableTest(countries, "Belgium, AREA: 30510.0", "Thailand, AREA: 513120.0");
    }

    public static void runGetMeasureTest(Measurable m, double expected) {
        System.out.println("Testing on " + m);
        double output = m.getMeasure();

        printTestResult(testDoubleOutput("getMeasure", output, expected, 0.1));
    }

    public static void runMeasurableTest(Measurable [] measurables, String expectedMin, String expectedMax) {
        System.out.println("Testing on " + Arrays.toString(measurables));
        String outputMin = Measurable.smallest(measurables).toString();

        boolean pass = true;
        if(!testStringOutput("Measurable.smallest", outputMin, expectedMin)) {
            pass = false;
        }

        String outputMax = Measurable.largest(measurables).toString();
        if(!testStringOutput("Measurable.largest", outputMax, expectedMax)) {
            pass = false;
        }

        printTestResult(pass);
    }

    public static void printTestResult(boolean pass)
    {
        if (pass) {
            System.out.println("*** TEST PASSES ***\n");
        } else {
            System.out.println("*******************************************");
            System.out.println("*************** TEST FAILED ***************");
            System.out.println("*******************************************\n");
        }
    }

    public static boolean testDoubleOutput(String methodName, double output, double expected, double epsilon)
    {
        System.out.println("OUTPUT of " + methodName + ":   " + output);
        if (Math.abs(output - expected) > epsilon) {
            System.out.println("EXPECTED of " + methodName + ": " + expected);
            System.out.println("    INCORRECT OUTPUT");
            return false;
        }
        return true;
    }

    public static boolean testStringOutput(String methodName, String output, String expected)
    {
        System.out.println("OUTPUT of " + methodName + ":   " + output);
        if (!output.equals(expected)) {
            System.out.println("EXPECTED of " + methodName + ": " + expected);
            System.out.println("    INCORRECT OUTPUT");
            return false;
        }
        return true;
    }
}
